# Generated by Django 5.0.6 on 2024-08-17 18:46

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timetableapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="week_day",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                ],
                max_length=2000,
            ),
        ),
    ]
